spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
server:
  port: 8057

logging:
  file:
    name: logs/angapp.log
    path: angapp
  level:
    com.geppetto: info
  pattern:
    dateformat: "dd-MM-yyyy hh:mm:ss aa"



























